todo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("todos.urls")),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todos/urls.py
from django.urls import path
from .views import TodoListView, TodoDeleteView, TodoCreateView, todo_update_status

app_name = "todos"

urlpatterns = [
    path("", TodoListView.as_view(), name="home"),
    path("todos/create/", TodoCreateView.as_view(), name="todo-create"),
    path("todos/<int:pk>/delete", TodoDeleteView.as_view(), name="todo-delete"),
    path("todos/<int:todo_id>/update-status",
         todo_update_status, name="todo-update-status"),
]

users/urls.py
from django.urls import path
from .views import login, logout, register

app_name = "users"

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
]

todos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Todo(models.Model):

    title = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.title} - {self.user.username}'

users/models.py
from django.db import models

# Create your models here.

todos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, CreateView
from .models import Todo
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages


# Create your views here.


class TodoListView(LoginRequiredMixin, ListView):
    model = Todo
    context_object_name = "todos"

    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user).order_by("completed", "-date_created")


class TodoDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Todo

    success_url = '/'

    def test_func(self):
        todo = self.get_object()

        if self.request.user == todo.user:
            return True

        return False

    def delete(self, request, *args, **kwargs):
        messages.info(self.request, "Successfully deleted Todo!")
        return super().delete(request, *args, **kwargs)


class TodoCreateView(LoginRequiredMixin, CreateView):
    model = Todo
    fields = ["title"]

    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Successfully created Todo!")
        return super().form_valid(form)


@login_required()
def todo_update_status(request, todo_id):

    todos = Todo.objects.filter(user=request.user)
    todo = get_object_or_404(todos, pk=todo_id)

    todo.completed = not todo.completed

    todo.save()

    messages.success(request, "Successfully updated status!")

    return redirect('todos:home')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.


def register(request):

    if request.user.is_authenticated:
        return redirect("todos:home")

    elif request.method == "POST":
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        username = request.POST["username"]
        email = request.POST["email"]
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username taken")
                return redirect("users:register")

            elif User.objects.filter(email=email).exists():
                messages.info(request, "Email already taken")
                return redirect("users:register")
            else:
                user = User.objects.create_user(
                    username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                user.save()
                print("user created")
                messages.success(request, "Successfully created account")
                return redirect("users:login")

        else:
            messages.info(request, "Passwords don't match")
            return redirect("users:register")

    return render(request, "users/register.html")


def login(request):

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            messages.success(request, "Successfully logged in!")
            return redirect("todos:home")

        else:
            messages.info(request, "Invalid Credentials")
            return redirect("users:login")

    elif request.user.is_authenticated:
        return redirect("todos:home")

    return render(request, "users/login.html")


@login_required(login_url="users:login")
def logout(request):
    auth_logout(request)
    messages.success(request, "Successfully logged out")
    return redirect("users:login")

todos/templates/todos/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />

    <script
      src="https://kit.fontawesome.com/2fa0defabe.js"
      crossorigin="anonymous"
    ></script>

    <link rel="stylesheet" href="{% static 'todos/css/style.css' %}" />

    <link
      rel="shortcut icon"
      href="{% static 'todos/images/favicon.jpeg' %}"
      type="image/x-icon"
    />

    <title>Todo App</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todos:home' %}"><i class="fas fa-th-list"></i> Todo App</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarText"
          aria-controls="navbarText"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% comment %}
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            {% endcomment %} {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todos:todo-create' %}"
                >New Todo</a
              >
            </li>
            {% endif %}
          </ul>
          <div class="d-flex">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}"
                  >Register</a
                >
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      {% if messages %} {% for message in messages %}

      <div
        class="col-md-6 alert alert-{{message.tags}} mx-auto mt-2"
        role="alert"
      >
        {{message}}
      </div>

      {% endfor %} {% endif %} {% block content %}{% endblock content %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

todos/templates/todos/todo_confirm_delete.html
{% extends 'todos/base.html' %} {% block content %}

<div class="row d-flex justify-content-center mt-3">
  <div class="col-md-6">
    <h3>Confirm Delete</h3>
    <hr />
    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Delete Todo</label>
      </div>
      <button type="submit" class="btn btn-danger">Delete</button>
      <a
        class="btn btn-outline-secondary"
        href="{% url "todos:home" %}"
        >Cancel</a
      >
    </form>
  </div>
</div>

{% endblock content %}

todos/templates/todos/todo_form.html
{% extends 'todos/base.html' %} {% load crispy_forms_tags %} {% block content %}

<div class="row d-flex justify-content-center mt-3">
  <div class="col-md-6">
    <h3>Create New Todo</h3>
    <hr />
    <form method="post">
      {% csrf_token %} {{form | crispy }}
      <button type="submit" class="btn btn-success mt-3">Create</button>
    </form>
  </div>
</div>

{% endblock content %}

todos/templates/todos/todo_list.html
{% extends 'todos/base.html' %} {% block content %}

<div class="d-flex flex-column align-items-center mt-3">
  <h3><i class="fas fa-list-alt"></i> Your Todos</h3>
  <hr />
  {% for todo in todos %}
  <div class="card mt-1 mb-2 col-sm-12 col-md-6 custom-width">
    <div class="card-body d-flex justify-content-between">
      <p class="card-text">
        {% if todo.completed %}
        <del>{{todo.title}}</del>
        {% else %} {{todo.title}} {% endif %}
      </p>
      <div class="">
        {% if todo.completed %}
        <a
          href="{% url 'todos:todo-update-status' todo.id %}"
          class="btn btn-warning"
          ><i class="fas fa-times"></i></a
        >
        {% else %}
        <a
          href="{% url 'todos:todo-update-status' todo.id %}"
          class="btn btn-success"
          ><i class="fas fa-check"></i></a
        >
        {% endif %}
        <a href="{% url 'todos:todo-delete' todo.id %}" class="btn btn-danger"
          ><i class="fas fa-trash"></i></a
        >
      </div>
    </div>
  </div>

  {% endfor %} {% if is_paginated %}

  <nav class="mt-2" aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.previous_page_number}}"
          >Prev</a
        >
      </li>

      {% endif %}
      
      {% for num in page_obj.paginator.page_range %}
       {% if page_obj.number == num %}
          <li class="page-item active">
            <a class="page-link" href="?page={{num}}">{{num}}</a>
          </li>
        {% elif num > page_obj.number|add:'-1' and num < page_obj.number|add:'1' %}
          <li class="page-item">
            <a class="page-link" href="?page={{num}}">{{num}}</a>
          </li>

        {% endif %} 
      {% endfor %}
     {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.paginator.num_pages}}"
          >{{page_obj.paginator.num_pages}}</a
        >
      </li>

      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'todos/base.html' %} {% block content %}

<div class="row d-flex justify-content-center mt-3">
  <div class="col-md-6">
    <h3>Login Here</h3>
    <hr />
    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Username</label>
        <input
          type="text"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          name="username"
        />
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input
          type="password"
          class="form-control"
          id="exampleInputPassword1"
          name="password"
        />
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</div>

{% endblock content %}

users/templates/users/register.html
{% extends 'todos/base.html' %} {% block content %}

<div class="row d-flex justify-content-center mt-3 mb-4">
  <div class="col-md-6">
    <h3>Register Here</h3>
    <hr />
    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">First Name</label>
        <input
          type="text"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          name="first_name"
        />
      </div>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Last Name</label>
        <input
          type="text"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          name="last_name"
        />
      </div>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email</label>
        <input
          type="email"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          name="email"
        />
      </div>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Username</label>
        <input
          type="text"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          name="username"
        />
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input
          type="password"
          class="form-control"
          id="exampleInputPassword1"
          name="password1"
        />
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label"
          >Confirm Password</label
        >
        <input
          type="password"
          class="form-control"
          id="exampleInputPassword1"
          name="password2"
        />
      </div>
      <button type="submit" class="btn btn-primary">Register</button>
    </form>
  </div>
</div>

{% endblock content %}